# Generated by Django 5.2.4 on 2025-08-10 07:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile-photo')),
                ('password', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Login faqat 12 ta raqamdan iborat bo'lishi kerak.", regex='^\\d{12}$')])),
                ('pasport', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Pasport ma'lumotlari xato kiritildi. (N: AD1234567)", regex='^[A-Za-z]{2}\\d{7}$')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami xato kiritildi. (N: +998901234567)', regex='^\\+998\\d{9}$')])),
                ('position', models.CharField(choices=[('assistent', "O'qituvchi"), ('senior', "Katta o'qituvchi"), ('docent', 'Dotsent (PhD)'), ('professor', 'Professor'), ('head_of_department', 'Kafedra mudiri'), ('dean', 'Fakultet dekani')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile-photo')),
                ('password', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Login faqat 12 ta raqamdan iborat bo'lishi kerak.", regex='^\\d{12}$')])),
                ('pasport', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Pasport ma'lumotlari xato kiritildi. (N: AD1234567)", regex='^[A-Za-z]{2}\\d{7}$')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami xato kiritildi. (N: +998901234567)', regex='^\\+998\\d{9}$')])),
                ('edu_type', models.CharField(choices=[('grant', 'Davlat granti asosida'), ('contract', 'To‘lov-kontrakt asosida')], max_length=12)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_attendances', to='main.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.student')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maked_attendances', to='main.teacher')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
