# Generated by Django 5.2.4 on 2025-07-09 13:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='profile-photo')),
                ('login', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_login', message='Login faqat 10 xonali raqamlardan iborat bo‘lishi kerak.', regex='^\\d{10}$')])),
                ('paspost', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Pasport raqamingizni to'g'ri kiriting. Masalan: AB1234567", regex='^[A-Za-z]{2}\\d{7}$')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanib, jami 13 ta belgidan iborat bo‘lishi kerak (masalan: +998901234567)', regex='^\\+998\\d{9}$')])),
                ('password', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.group')),
            ],
        ),
    ]
