# Generated by Django 5.2.4 on 2025-07-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='paspost',
            new_name='pasport',
        ),
    ]
