# Generated by Django 5.2.4 on 2025-07-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_paspost_students_pasport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
