# Generated by Django 5.2.4 on 2025-07-10 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_on',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
