# Generated by Django 5.2.4 on 2025-07-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_attendance_created_on_attendance_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
